### ISSUE TITLE
Seems a wrong implementation of coef's gradient calculation

### ISSUE THREAD

**Issue by yunzhi-teng** [BoChenYS/BPnP#5]
Hi，Bo Chen, 

We are currently following your excellent work BPNP. And we have a question about your eq(17,18,20,21,22). In eq. 17,  c_ij in f_j is calculated from y , so it must have derivative with respect to y. But in your code, you don't account for the derivative and just return a coef without computational graph.

We have tested that your implementation y_grad = torch.autograd.grad(proj[:,:,k],y,vec, retain_graph=True) will not give y_grad a grad_fn, unless change it into

y_grad = torch.autograd.grad(proj[:,:,k],y,vec, retain_graph=True,create_graph=True)

I wonder how you think about this question, have you tested it?

**And we have tested our modified implementation and the results show that it has a significant improve on convergence rate in your PoseEstimation and CamCalib demo.** 

Thank you!

**Comment by yunzhi-teng** [comment]
The convergence rate seems not stable when testing multiple times. Do you have some advice to explain this question?

**Comment by BoChenYS** [comment]
Hi Yunzhi, you are right. In the get_coefs function the create_graph needs to be set to True and return a coef with graph. Thank you very much for spotting this error. I have fixed the code now. 

You said the convergence rate seems not stable, I am not sure what is your modification and cannot give an explanation. I have tested the updated code, and there seems to be no difference with the previous version, except that it is obviously slower now, because in the backward pass I now have to put the call of the get_coefs() function inside the 'j' for-loop. Therefore, I have created a new class BPnP_fast, which is basically the previous version that ignores the higher order derivatives from the coefs' graph. I think sacrificing negligible gradient accuracy in exchange for efficient runtime might be useful sometimes.
